/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "var(--color-on-error)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "secondary-dim": "var(--color-secondary-dim)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "secondary": "var(--color-secondary)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-primary-container": "var(--color-on-primary-container)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface": "var(--color-surface)",
        "on-error-container": "var(--color-on-error-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "surface-tint": "var(--color-surface-tint)",
        "error-dim": "var(--color-error-dim)",
        "primary-container": "var(--color-primary-container)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-secondary": "var(--color-on-secondary)",
        "tertiary-dim": "var(--color-tertiary-dim)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-surface": "var(--color-on-surface)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "surface-container-low": "var(--color-surface-container-low)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "background": "var(--color-background)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-variant": "var(--color-surface-variant)",
        "on-primary": "var(--color-on-primary)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "outline": "var(--color-outline)",
        "surface-bright": "var(--color-surface-bright)",
        "primary-dim": "var(--color-primary-dim)",
        "tertiary": "var(--color-tertiary)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "outline-variant": "var(--color-outline-variant)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-background": "var(--color-on-background)",
        "primary": "var(--color-primary)",
        "error": "var(--color-error)",
        "surface-container": "var(--color-surface-container)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "inverse-primary": "var(--color-inverse-primary)",
        "secondary-container": "var(--color-secondary-container)",
        "surface-dim": "var(--color-surface-dim)",
        "error-container": "var(--color-error-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-tertiary": "var(--color-on-tertiary)"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
